pipeline {
    agent any

    stages {
        stage('GIT') {
            steps {
                git branch: 'sami-sellami', url: 'https://github.com/yossraa123/tp-foyer.git', credentialsId: 'github-creds'
            }
        }

        stage('Test Docker Access') {
            agent {
                docker { image 'docker:20.10.8' } // Use a Docker image for this stage
            }
            steps {
                sh "docker --version"
            }
        }
    }
}
